version: "3"
services:
    nginx:
       image: "nginx"    
       volumes:
       - "./hosts.conf:/etc/nginx/conf.d/default.conf"
       - "/var/www/html:/var/www/html"
       ports:
       - "80:80"
       links:
       - "php"
    php:
       image: "binhle410/php7.2-fpm"
       volumes:
       - "/var/www/html:/var/www/html"
       ports:
       - "9000:9000"
